In [4]:
import requests
import pandas as pd

In [5]:
url = "https://opendata.tpg.ch/api/explore/v2.1/catalog/datasets/montees-par-arret-par-ligne/records"

params = {
    "limit" : 5,
}

In [6]:
response = requests.get(url, params=params)

response.status_code

200

In [7]:
data = response.json()
data

{'total_count': 4585748,
 'results': [{'date': '2026-06-27',
   'ligne': '1',
   'ligne_type_act': 'PRINCIPAL',
   'jour_semaine': '6-Samedi',
   'horaire_type': 'SAMEDI',
   'arret': '31 Décembre',
   'arret_code_long': '31DC01',
   'nb_de_montees': 205.8200000000001,
   'nb_de_descentes': 200.33,
   'donnees_definitives': 'True',
   'indice_jour_semaine': 6,
   'coordonnees': {'lon': 6.162252, 'lat': 46.201778}},
  {'date': '2026-06-27',
   'ligne': '1',
   'ligne_type_act': 'PRINCIPAL',
   'jour_semaine': '6-Samedi',
   'horaire_type': 'SAMEDI',
   'arret': 'Belle-Idée-Centre',
   'arret_code_long': 'BLID00',
   'nb_de_montees': 69.66999999999999,
   'nb_de_descentes': 11.55,
   'donnees_definitives': 'True',
   'indice_jour_semaine': 6,
   'coordonnees': {'lon': 6.20993, 'lat': 46.207157}},
  {'date': '2026-06-27',
   'ligne': '1',
   'ligne_type_act': 'PRINCIPAL',
   'jour_semaine': '6-Samedi',
   'horaire_type': 'SAMEDI',
   'arret': 'Belle-Terre-Ecole',
   'arret_code_long': 'BTEC01',
   'nb_de_montees': 13.5,
   'nb_de_descentes': 2.07,
   'donnees_definitives': 'True',
   'indice_jour_semaine': 6,
   'coordonnees': {'lon': 6.210109, 'lat': 46.202099}},
  {'date': '2026-06-27',
   'ligne': '1',
   'ligne_type_act': 'PRINCIPAL',
   'jour_semaine': '6-Samedi',
   'horaire_type': 'SAMEDI',
   'arret': 'Belle-Terre-Ecole',
   'arret_code_long': 'BTEC00',
   'nb_de_montees': 1.01,
   'nb_de_descentes': 11.31,
   'donnees_definitives': 'True',
   'indice_jour_semaine': 6,
   'coordonnees': {'lon': 6.210499, 'lat': 46.20203}},
  {'date': '2026-06-27',
   'ligne': '1',
   'ligne_type_act': 'PRINCIPAL',
   'jour_semaine': '6-Samedi',
   'horaire_type': 'SAMEDI',
   'arret': "Belle-Terre-Place-de-l'Araire",
   'arret_code_long': 'BTPA01',
   'nb_de_montees': 34.39,
   'nb_de_descentes': 2.01,
   'donnees_definitives': 'True',
   'indice_jour_semaine': 6,
   'coordonnees': {'lon': 6.218457, 'lat': 46.206551}}]}

In [8]:
df = pd.DataFrame(data["results"])
df

,date,ligne,ligne_type_act,jour_semaine,horaire_type,arret,arret_code_long,nb_de_montees,nb_de_descentes,donnees_definitives,indice_jour_semaine,coordonnees
0,2026-06-27,1,PRINCIPAL,6-Samedi,SAMEDI,31 Décembre,31DC01,205.82,200.33,True,6,"{'lon': 6.162252, 'lat': 46.201778}"
1,2026-06-27,1,PRINCIPAL,6-Samedi,SAMEDI,Belle-Idée-Centre,BLID00,69.67,11.55,True,6,"{'lon': 6.20993, 'lat': 46.207157}"
2,2026-06-27,1,PRINCIPAL,6-Samedi,SAMEDI,Belle-Terre-Ecole,BTEC01,13.50,2.07,True,6,"{'lon': 6.210109, 'lat': 46.202099}"
3,2026-06-27,1,PRINCIPAL,6-Samedi,SAMEDI,Belle-Terre-Ecole,BTEC00,1.01,11.31,True,6,"{'lon': 6.210499, 'lat': 46.20203}"
4,2026-06-27,1,PRINCIPAL,6-Samedi,SAMEDI,Belle-Terre-Place-de-l'Araire,BTPA01,34.39,2.01,True,6,"{'lon': 6.218457, 'lat': 46.206551}"

In [9]:
df.shape

(5, 12)

In [10]:
df.columns.tolist()

['date',
 'ligne',
 'ligne_type_act',
 'jour_semaine',
 'horaire_type',
 'arret',
 'arret_code_long',
 'nb_de_montees',
 'nb_de_descentes',
 'donnees_definitives',
 'indice_jour_semaine',
 'coordonnees']

In [11]:
df.dtypes

date                       str
ligne                      str
ligne_type_act             str
jour_semaine               str
horaire_type               str
arret                      str
arret_code_long            str
nb_de_montees          float64
nb_de_descentes        float64
donnees_definitives        str
indice_jour_semaine      int64
coordonnees             object
dtype: object

In [12]:
df.isna().sum()

date                   0
ligne                  0
ligne_type_act         0
jour_semaine           0
horaire_type           0
arret                  0
arret_code_long        0
nb_de_montees          0
nb_de_descentes        0
donnees_definitives    0
indice_jour_semaine    0
coordonnees            0
dtype: int64

In [13]:
data["total_count"]

4585748

In [14]:
date_params = {
    "select": "min(date) as min_date, max(date) as max_date"
}

date_response = requests.get(
    url,
    params=date_params,
    timeout=30
)

date_response.status_code

200

In [15]:
date_data = date_response.json()
date_data["results"]

[{'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'},
 {'min_date': '2023-02-01T00:00:00+00:00',
  'max_date': '2026-09-14T00:00:00+00:00'}]

In [16]:
date_range = date_data["results"][0]
date_range

{'min_date': '2023-02-01T00:00:00+00:00',
 'max_date': '2026-09-14T00:00:00+00:00'}

In [17]:
min_date = pd.Timestamp(date_range["min_date"]).tz_convert(None)
max_date = pd.Timestamp(date_range["max_date"]).tz_convert(None)

months = pd.period_range(
    min_date.to_period("M"),
    max_date.to_period("M"),
    freq="M"
)

months

PeriodIndex(['2023-02', '2023-03', '2023-04', '2023-05', '2023-06', '2023-07',
             '2023-08', '2023-09', '2023-10', '2023-11', '2023-12', '2024-01',
             '2024-02', '2024-03', '2024-04', '2024-05', '2024-06', '2024-07',
             '2024-08', '2024-09', '2024-10', '2024-11', '2024-12', '2025-01',
             '2025-02', '2025-03', '2025-04', '2025-05', '2025-06', '2025-07',
             '2025-08', '2025-09', '2025-10', '2025-11', '2025-12', '2026-01',
             '2026-02', '2026-03', '2026-04', '2026-05', '2026-06', '2026-07',
             '2026-08', '2026-09'],
            dtype='period[M]')

In [ ]:
monthly_counts = []

for month in months:
    start_date = month.start_time.strftime("%Y-%m-%d")
    next_month = (month + 1).start_time.strftime("%Y-%m-%d")

    params = {
        "where": (
            f"date >= date'{start_date}' "
            f"AND date < date'{next_month}'"
        ),
        "limit": 1
    }

    response_month = requests.get(
        url,
        params=params,
        timeout=30
    )

    response_month.raise_for_status()

    monthly_counts.append({
        "month": str(month),
        "records": response_month.json()["total_count"]
    })

In [19]:
monthly_counts_df = pd.DataFrame(monthly_counts)

monthly_counts_df

      month  records
0   2023-02    97707
1   2023-03   111225
2   2023-04   101552
3   2023-05   108304
4   2023-06   106598
5   2023-07   102994
6   2023-08   104900
7   2023-09   105994
8   2023-10   107243
9   2023-11   105035
10  2023-12   105334
11  2024-01   104798
12  2024-02    98310
13  2024-03   104319
14  2024-04    98960
15  2024-05   104298
16  2024-06   100599
17  2024-07    99771
18  2024-08   102946
19  2024-09   103674
20  2024-10   106946
21  2024-11   104986
22  2024-12   105669
23  2025-01   107549
24  2025-02    96549
25  2025-03   107540
26  2025-04   100656
27  2025-05   106875
28  2025-06   103747
29  2025-07   102786
30  2025-08   105888
31  2025-09   108071
32  2025-10   109900
33  2025-11   106831
34  2025-12   109800
35  2026-01   113073
36  2026-02   100926
37  2026-03   113957
38  2026-04   106019
39  2026-05   112535
40  2026-06   109576
41  2026-07   107381
42  2026-08   111926
43  2026-09    52001

In [20]:
monthly_counts_df["records"].sum()

np.int64(4585748)

need monthly reusable monthly downloader

In [21]:
from pathlib import Path

In [22]:
export_url = (
    "https://opendata.tpg.ch/api/explore/v2.1/catalog/datasets/"
    "montees-par-arret-par-ligne/exports/csv"
)

In [23]:
def download_month(month):
    period = pd.Period(month, freq="M")

    start_date = period.start_time.strftime("%Y-%m-%d")
    next_month = (period + 1).start_time.strftime("%Y-%m-%d")

    params = {
        "where": (
            f"date >= date'{start_date}' "
            f"AND date < date'{next_month}'"
        ),
        "delimiter": ","
    }

    response = requests.get(
        export_url,
        params=params,
        timeout=120
    )

    response.raise_for_status()

    return response

TESTING for a month

In [24]:
test_response = download_month("2026-08")

len(test_response.content)

12231838

In [25]:
test_response.text[:500]

'\ufeffdate,ligne,ligne_type_act,jour_semaine,horaire_type,arret,arret_code_long,nb_de_montees,nb_de_descentes,donnees_definitives,indice_jour_semaine,coordonnees\r\n2026-08-07,1,PRINCIPAL,5-Vendredi,VACANCES,Belle-Idée-Centre,BLID00,58.58,0.0,False,5,"46.207157, 6.20993"\r\n2026-08-07,1,PRINCIPAL,5-Vendredi,VACANCES,Belle-Idée-Réception,BISA00,23.58000000000001,2.06,False,5,"46.205853, 6.207407"\r\n2026-08-07,1,PRINCIPAL,5-Vendredi,VACANCES,Castan,CAST01,17.81,161.89,False,5,"46.206261, 6.196694"\r\n2026-08-'

In [26]:
from pathlib import Path

output_path = Path("../data/raw/tpg/2026")
output_path.mkdir(parents=True, exist_ok=True)

file_path = output_path / "2026-08.csv"

with open(file_path, "wb") as f:
    f.write(test_response.content)

file_path

WindowsPath('../data/raw/tpg/2026/2026-08.csv')

In [27]:
august_df = pd.read_csv(file_path, encoding="utf-8-sig")

august_df.head()

,date,ligne,ligne_type_act,jour_semaine,horaire_type,arret,arret_code_long,nb_de_montees,nb_de_descentes,donnees_definitives,indice_jour_semaine,coordonnees
0,2026-08-07,1,PRINCIPAL,5-Vendredi,VACANCES,Belle-Idée-Centre,BLID00,58.58,0.00,False,5,"46.207157, 6.20993"
1,2026-08-07,1,PRINCIPAL,5-Vendredi,VACANCES,Belle-Idée-Réception,BISA00,23.58,2.06,False,5,"46.205853, 6.207407"
2,2026-08-07,1,PRINCIPAL,5-Vendredi,VACANCES,Castan,CAST01,17.81,161.89,False,5,"46.206261, 6.196694"
3,2026-08-07,1,PRINCIPAL,5-Vendredi,VACANCES,"Chêne-Bougeries, Rigaud",CEPR01,47.95,228.43,False,5,"46.203876, 6.187355"
4,2026-08-07,1,PRINCIPAL,5-Vendredi,VACANCES,Cirque,CIRQ01,416.01,282.51,False,5,"46.200806, 6.140586"

In [28]:
august_df.shape

(111926, 12)

In [29]:
len(august_df)

111926

In [30]:
august_df["date"].min(), august_df["date"].max()

('2026-08-01', '2026-08-31')

In [32]:
august_df.isna().sum()

date                   0
ligne                  0
ligne_type_act         0
jour_semaine           0
horaire_type           0
arret                  0
arret_code_long        0
nb_de_montees          0
nb_de_descentes        0
donnees_definitives    0
indice_jour_semaine    0
coordonnees            0
dtype: int64

In [33]:
download_month("2026-08")

In [34]:
download_and_save_month("2026-08")

NameError: name 'download_and_save_month' is not defined